# Generated by Django 4.0.3 on 2022-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='document',
            field=models.FileField(default=True, upload_to='documents/'),
        ),
    ]
