# Generated by Django 4.0.3 on 2022-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_description_journal_link_journal_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
