# Generated by Django 4.0.3 on 2022-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
