# Generated by Django 4.0.3 on 2022-03-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='tags',
        ),
    ]
