# Generated by Django 4.0.3 on 2022-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journal_tags_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
