# Generated by Django 4.0.3 on 2022-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_remove_journal_slug_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
