# Generated by Django 4.0.3 on 2022-03-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_post_description_remove_post_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
