# Generated by Django 4.0.3 on 2022-03-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_remove_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
