# Generated by Django 4.0.3 on 2022-03-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='tags',
        ),
    ]
