# Generated by Django 4.0.3 on 2022-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
