# Generated by Django 4.0.3 on 2022-03-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_journal_options_journal_file_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='file',
        ),
    ]
